# SPDX-License-Identifier: GPL-2.0

obj-y += checkpoint.o dentry.o file.o hlist.o inode.o list.o object.o skiplist.o transaction.o

obj-$(CONFIG_TRANSACTIONS_KUNIT_TEST) += checkpoint_test.o hlist_test.o skiplist_test.o transaction_test.o
